#!/usr/bin/env bash
# Script to install nginx and configure it to serve a custom index
apt-get update -y
apt-get install nginx -y
service nginx start
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

